package com.nvgroupitech.truelove.utils;

import java.io.IOException;
import java.util.Map;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit4.SpringRunner;

import com.nvgroupitech.truelove.TrueloveApplication;
import com.nvgroupitech.truelove.utils.utils.JwtTokenUtils;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = TrueloveApplication.class)
@AutoConfigureMockMvc
@TestPropertySource(
  locations = "classpath:application-integrationtest.properties")
public class JwtTokenUtilsTest {
	@Test
	public void testExtract() throws IOException {
		String jwtToken="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMWnpISDVlOERQSjlkbHBFWnI4MVBGNVJaSW5ONDA5VmZNdFNCNnFaZTRNIn0.eyJleHAiOjE2MzQxMzQ1ODYsImlhdCI6MTYzNDA5ODU4NiwianRpIjoiMzhkNDFmMjgtN2U4Yy00ZjQyLWEzNzctOTlkOWMyYTU3MzQyIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5udmdyb3VwaXRlY2gub3JnL2F1dGgvcmVhbG1zL3RydWVsb3ZlIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjIyYjI3MmJiLTY4MTEtNDdjOS1hMjVjLWU0YTE0OTY0NmRlOSIsInR5cCI6IkJlYXJlciIsImF6cCI6InRydWVsb3ZlLWFwcCIsInNlc3Npb25fc3RhdGUiOiJkZjlhMjg2ZC05ODU4LTQ4ZTItOWI3My1hNDViM2FhZGY3NGUiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8va2V5Y2xvYWsubnZncm91cGl0ZWNoLm9yZyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy10cnVlbG92ZSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJkZjlhMjg2ZC05ODU4LTQ4ZTItOWI3My1hNDViM2FhZGY3NGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InVzcjAwMDAxNDUiLCJlbWFpbCI6Im5nb2NudnRlY2hAZ21haWwuY29tIn0.vht9pJukFEuXAASffHqYezPKiP1jrSfhb5fkHDl8YrAcX72yOIvN9YbWaGKxVykAqrh6uFXhax72WSBaXfnQgakjPjzjFLe4SDbQ9TwbR4f1-93lW2vopcgMCPx2MDy_v624tv1r7GwEfSAQzX3Spm-juZipQ9Il6u7XwrdRkGzSu1TFkEbkgjoe7VIXFN3u6F3ZhVhXWVw6LGJrXwqAZsVTJWft91iQNIstkM0yS5Cjm8ync8Yq-QUWfAkl9vt7JgNqTJ7M6ssL3gJS3W2e42mioGa_XajI1sqseNDh7K1IFwhejUNeN2EvAke59k6JZ-Zs_FMW249uhW14tgm8dw";
		Map<String,Object> maps = JwtTokenUtils.extract(jwtToken);
		System.out.println(maps.get("preferred_username"));
	}
}
